version: "3.8"

services:
  backend:
    container_name: weather_api_backend
    build:
      context: ./weather_api
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./weather_api:/weather_api_backend
    ports:
      - 8000:8000
    env_file:
      - ./.env
